name: textutils
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pytest
  - pygments
  - packaging
  - pip
  - bzip2
  - ca-certificates
  - coverage
  - expat
  - iniconfig
  - libffi
  - libzlib
  - ncurses
  - openssl
  - packaging
  - pluggy
  - pytest-cov
  - readline
  - setuptools
  - sqlite
  - tk
  - toml
  - tzdata
  - wheel
  - xz
  - zlib